
```{r}
# Install packages (if not already installed)
# install.packages("devtools")
devtools::install_github("fennicahub/finna") 
devtools::install_github("fennicahub/finto")
install.packages("dplyr")
install.packages("ggplot2")
```

```{r}
library(finna)
library(finto)
library(dplyr)
library(ggplot2)
```

```{r}
# Search for items related to "music"
music_rec <- search_finna("music")
head(music_rec)
```

```{r}

# Basic plot: number of items by institution
music_rec %>% 
  count(Library) %>% 
  ggplot(aes(x = reorder(Library, n), y = n)) +
  geom_col() +
  coord_flip() +
  labs(title = "Items by Library", x = NULL, y = "Count")
```

```{r}
data("fennica_subset",package = "finna")
tail(fennica_subset)
```

```{r}
# Load a sample dataset
fennica_subset <- tail(fennica_subset)

# Enrich authors with Kanto info
authors_kanto <- finto::get_kanto(fennica_subset)
head(authors_kanto)
```

```{r}
# Annotate a short text with YSO concepts
text <- "climate change and biodiversity loss"
suggest_subjects(text, project = "yso-en")
```

```{r}
hierarchy <- get_hierarchy(vocid = "yso", uri = "http://www.yso.fi/onto/yso/p5729", lang = "en")
print(hierarchy)
```

```{r}

```

